### ISSUE TITLE
Link to report not shown when a task is completed with an error

### ISSUE THREAD

**Issue by boris-petrov** [KengoTODA/spotbugs-gradle-plugin-v2#102]
The old plugin printed a useful message with a `file://...` link to the generated HTML report that I could copy-paste to my browser easily. I cannot live without this so please implement it! :) Here is my configuration if you think I'm missing something:

```groovy
spotbugs {
	effort = 'max'
	reportLevel = 'low'
	excludeFilter = file("${projectDir}/src/config/spotbugs/excludeFilter.xml")
}

tasks.withType(SpotBugsTask) {
	reports {
		html.enabled = true
	}
}
```

**Comment by KengoTODA** [comment]
Why not contribute by own 😀 
Maybe you can refer this part in the legacy plugin project:

https://github.com/spotbugs/spotbugs-gradle-plugin/blob/3d91ea90a07ab0895a740d8af37bc9f11711b079/src/main/java/com/github/spotbugs/SpotBugsTask.java#L328-L329

**Comment by KengoTODA** [comment]
Ah, but, the `ConsoleRenderer` is internal API then we cannot use it...

**Comment by KengoTODA** [comment]
I'll archive this repository, please issue a new PR at [the official repository](https://github.com/spotbugs/spotbugs-gradle-plugin).
