### ISSUE TITLE
spotbugsMain always runs

### ISSUE THREAD

**Issue by jscancella** [KengoTODA/spotbugs-gradle-plugin-v2#109]
when I run `.gradlew spotbugsMain` twice in a row (no code changes in between), I would have expected it to say `1 actionable task: 1 up-to-date`, instead it runs it again. While not a show stopper, we should probably fix whatever is causing it to always evaluate it to be out of date and run.

**Comment by KengoTODA** [comment]
we already have [an automated test to check this behaviour](https://github.com/KengoTODA/spotbugs-gradle-plugin-v2/blob/3b6f8cffef6aec92d3a21e1ef31ef9858d005700/src/functionalTest/groovy/com/github/spotbugs/snom/StandardFunctionalTest.groovy#L190), and it passes in each CI build. Could you find a way to reproduce?

**Comment by KengoTODA** [comment]
I'll archive this repository, please issue a new PR at [the official repository](https://github.com/spotbugs/spotbugs-gradle-plugin).
