### ISSUE TITLE
Tasks are not generated when Java Plugin is not yet applied

### ISSUE THREAD

**Issue by rpalcolea** [KengoTODA/spotbugs-gradle-plugin-v2#32]
Hi @KengoTODA ,

I found the following issue... Given this build file:

```
plugins {
    id 'java'
    id "jp.skypencil.spotbugs.snom" version "0.4.4"
}

repositories {
    jcenter()
}

spotbugsMain {
    reports {
        html {
            enabled = true
            destination = file("$buildDir/reports/spotbugs/main/spotbugs.html")
            stylesheet = 'fancy-hist.xsl'
        }
    }
}
```

when running `./gradlew spotbugsMain`, we can see `Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method spotbugsMain() for arguments [build_f5cedp4ivv5m03bg1oasr92c$_run_closure2@3f569a72] on root project 'spotbugs-v2-test' of type org.gradle.api.Project.`

It seems like `JavaPluginConvention` is not available yet: https://github.com/KengoTODA/spotbugs-gradle-plugin-v2/blob/master/src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsTaskFactory.java#L46

Doing something like this works though:

```
buildscript {
    repositories {
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "gradle.plugin.com.github.spotbugs.snom:spotbugs-gradle-plugin-v2:0.4.4"
    }
}

plugins {
    id 'java'
}

allprojects {
    apply plugin: "jp.skypencil.spotbugs.snom"
}
```

**Comment by KengoTODA** [comment]
Seems strange, we have functional tests like this (StandardFunctionalTest) and they pass.
Could you share the version of your Gradle?

**Comment by rpalcolea** [comment]
This was with 6.0.1
