### ISSUE TITLE
spotbugsMain not Cacheable

### ISSUE THREAD

**Issue by foto-andreas** [KengoTODA/spotbugs-gradle-plugin-v2#41]
Hi,

the task spotbugsMain is not cacheable:

* It should declare its output (report). I did this manually with the task api as a workaround
* It uses the read only property firstEnabledReport which is an Optional. gradle (6.0.1) has problems with this:
`Non-cacheable input value property 'firstEnabledReport' was loaded with an unknown classloader (class 'java.util.Optional')..`

Currently I am testing with your new implementation on a large multi project build (around 1.3 mio loc) with parallel builds. The original implementation breaks some builds since we updated to gradle 6.0.1. 

Andreas

**Comment by KengoTODA** [comment]
#42 will make the task cache-able, however, to use build-cache we need a report.
I wonder we need to enable a report by default, but I leave it for future discussion at this moment.

**Comment by foto-andreas** [comment]
Thank you for the quick reaction. I think there is no need for a default output. It can be done by configuration if needed. Will try further with caching.
