### ISSUE TITLE
Unable to set effort to 'min'

### ISSUE THREAD

**Issue by cmuchinsky** [KengoTODA/spotbugs-gradle-plugin-v2#62]
Using identical code to the regular `spotbugs-gradle-plugin`, I see the following error reported when setting the effort to `'min'`:
```
A problem occurred evaluating script.
> Cannot cast object 'min' with class 'java.lang.String' to class 'org.gradle.api.provider.Property'
```

**Comment by cmuchinsky** [comment]
Scratch that, when I switched from the `2.0.0-SNAPSHOT` version to `0.4.13` I got further. The gradle plugins page has `2.0.0-SNAPSHOT` sorted on top so I was assuming it was the latest.

**Comment by KengoTODA** [comment]
Thanks for your report. 

> The gradle plugins page has 2.0.0-SNAPSHOT sorted on top so I was assuming it was the latest.

This is known issue and https://github.com/gradle/plugin-portal-requests/issues/30 will solve it.
