### ISSUE TITLE
Use same packaging as legacy plugin

### ISSUE THREAD

**Issue by rpalcolea** [KengoTODA/spotbugs-gradle-plugin-v2#65]
Hi @KengoTODA 

Wondering if you are planning to keep the same packaging: `com.github.spotbugs` and `com.github.spotbugs.internal` instead of `com.github.spotbugs.snom` and `com.github.spotbugs.snom.internal` as this might be a breaking change when doing the following on their build files:

```
tasks.withType(com.github.spotbugs.SpotBugsTask) {
  // configure automatically generated tasks
}
```

**Comment by KengoTODA** [comment]
Will be done when this plugin becomes stable.

**Comment by KengoTODA** [comment]
Ah, sorry but the package name will be kept as `com.github.spotbugs.snom` because the new plugin actually changes internal implementation. To avoid mixing classes in classpath and make the stacktrace intentional, I change the package name.
