### ISSUE TITLE
Task with name 'check' not found in root project

### ISSUE THREAD

**Issue by tir38** [KengoTODA/spotbugs-gradle-plugin-v2#77]
I thought I'd try to drop this in my Android project. In the root `build.gradle` file I add

```
buildscript {
    repositories {
         ...
    }
    dependencies {
        ...
    }
}

plugins {
    ...
    id "jp.skypencil.spotbugs.snom" version "2.0.0-SNAPSHOT"
}
```

I'm now getting this Gradle error

```
An exception occurred applying plugin request [id: 'jp.skypencil.spotbugs.snom', version: '2.0.0-SNAPSHOT']
> Failed to apply plugin [id 'jp.skypencil.spotbugs.snom']
   > Task with name 'check' not found in root project 'myProject'.
``` 

I'm guessing you are trying to add your task to the `check` task [here](https://github.com/KengoTODA/spotbugs-gradle-plugin-v2/blob/a31c6755239a9b579f16107ecfeb00a47dae53f7/src/main/groovy/com/github/spotbugs/snom/SpotBugsPlugin.java#L106) not sure why this is erroring though. Any thoughts?

Especially weird since I can confirm I do have a `check` task at root level:

```
$ ./gradlew tasks | grep check
> Task :buildSrc:check UP-TO-DATE
check - Runs all checks. // <--------------
connectedCheck - Runs all device checks on currently connected devices.
deviceCheck - Runs all device checks using Device Providers and Test Servers.
Kotlin plugin should be enabled before 'kotlin-android-extensions'
```
---------
Update:

Just for the hell of it I tried to put this inside the `app/build.gradle` file and  essentially same error

```
plugins {
    id 'com.android.application'
    ...
    id "jp.skypencil.spotbugs.snom" version "2.0.0-SNAPSHOT"
}
```

```
An exception occurred applying plugin request [id: 'jp.skypencil.spotbugs.snom', version: '2.0.0-SNAPSHOT']
> Failed to apply plugin [id 'jp.skypencil.spotbugs.snom']
   > Task with name 'check' not found in project ':app'.
```

**Comment by KengoTODA** [comment]
Use [v0.4.17](https://plugins.gradle.org/plugin/jp.skypencil.spotbugs.snom/0.4.17) instead of 2.0.0-SNAPSHOT. 

refs https://github.com/gradle/plugin-portal-requests/issues/30

**Comment by tir38** [comment]
Great that got rid of the error.
