### ISSUE TITLE
Not adding task to android gradle multi-module project

### ISSUE THREAD

**Issue by tir38** [KengoTODA/spotbugs-gradle-plugin-v2#85]
Now that I have the plugin added w/out crashing (#77 ) I'm unable to see the SpotBug task added. I have an Android multi-module project. I added this line to the root build.gradle:

```
plugins {
    ...
    id "jp.skypencil.spotbugs.snom" version "0.4.20"
}
```

However when I check for tasks none show up:

```
$ ./gradlew tasks --all | grep -i spot
```

**Comment by KengoTODA** [comment]
Can you share your project, or [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce?

**Comment by KengoTODA** [comment]
I'll close this stale issue, feel free reopen this with MCVE project.
